apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m0s
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-mangaer
      version: ">=1.9.1"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 5m0s
