apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 10m0s
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      version: '>=0.13.4'
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 5m0s