apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgAQiEpKQKnvcHenQUyHnPSkCZ6UCv5fi2mEd861eMAfQ4TWv2WVAmZBvpt7GR25UR76BhbaSl0RHgbZgP6+FmmGpgr1yuaD5J6TVGxAYE5ZFdmdh8262CPJPEWhqyOcL0QYOu01cknz4482u22tSVUEN2nViJM2PLVLFciMJ4aQBYxtRKaJF3wSXMicSy/XV59xkX9xNaXzHm2nvwyB3LRPIzvQuWD0wWA6Gac8p4K/eaxfPyh78oPYRh7igMj0XMtWjkgaO2Pokjk3ze95vg5W50guiYnAIofPJzzc7BxOSv9/c6cJtWtoeSgDTIgrl5+gmDDc1TexL05sagiwX9bchuglISnTyG9bic/9viFBqdiAudZOJ3AME147e+5tZNofcqoN+jP9zdnOO5timw41vxaUalctmj6Q06wLL4otxSU1aehBzIVShHWx01uEST3TvKECRPsze1imiadX6ZDAbZoWymubFYL8boVmCvtrEzmFBk96GpMQsduNaIex1nEoBsdQmIFAvq/+AyEtGhWnNAUUOZ/1M4L+27bZtWXtMW/8I7fUftU/84B8oeKFn9uCgJW/lZq4FdDUk2MSkBLszA6XgS35p6bYLXObds26Mh2s82267bmNm/X+yFh5qLM4oNPLXSNVko79M6QLl8q9nQP4Pw58f29M17rl4jZmTPD0VFhVpCj79fx/wfIdVNpA6SGjbPgKztHhXca1Bkw4SogxA7BC2INLqlk93XBrxOG7CpxS/vS0
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: opague

