apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgBzJPhQ/IhZtyVGqn27unNfaMXBlqJBiTtfRTAgrFOY0o9lbSN49P7O5CZ/lenOsCEnRIXAaeGOxkRzqo2YF46qFjLsmEayTkYuyNQ9v07+bfOM8Wht/7VC43L6FNAuGmNNyBnR+dTW0NvX4kSjl6SAVw5nwLYw1FdEr/smBVZqpRHdmpBT3ZQ5DcpEnpT0dNjOJHxg/36iZvTfgfA+zXeZFVKvA1styaU/AX9cBgT61pYoSC29WQcoDAbSjeVPGmHZHaPnxcAsDoWGI/W8mHVy98YUrJReXHR0r4tNUnMBhoCnA4l9DgJ5+XZNuZ8VIwleGESbTgMn3fUb9JywMZU9qtswDUEwtOnjmfrvd1yl6Qz8/FY7JMmBLM2/UQ+XbXfpqmtlRSZeXiz6WEm75wNMX28d2mCoC8gSiLSEOCFaXRPjTG/SoWtMHJe2mqxdaZmsUdTcG37QAAfk5I5QqskyDSJ7pjMABG2OkHbWBShS/3QaJXpqmPAZE/8WxJVPkCs/AkMzygzmDo8WL7UZTHi7CnxPh4vWuow2yHBKDccct/kOZ5YBRY6YCeO0bwL9lSu/nIIfpxtSisndaRO60TzS8NRMtYzJynZTKn1JUJ5z5bvVDIO5mBmLmUXkTpxFW/QN35qyqSZ0X0Z//I+dALGANyoUSdk6KfpeWXyplBfbRo2ah/WchN1stOP4dnUYFEKPNSA85CCHTSnJvLuazPzD5SBGZgoHSnt4e8kb4Qft7JXKAHMbMJvM
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: opague

