---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-danielvignoles-com
  namespace: default
spec:
  secretName: local-danielvignoles-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.danielvignoles.com"
  dnsNames:
  - "local.danielvignoles.com"
  - "*.local.danielvignoles.com"
